### PR TITLE
Implemented collapsible elements in scenegraph

### PR DESCRIPTION
**Pull request by Adam4lexander**
Implemented similarly to Unity. Click carrots to expand/collapse elements.
While searching all collapsed elements are expanded. When clearing the search the selected element will have its parent elements expanded.
I used a weakmap to store expanded/collapsed state on elements so there was no need to mess with the rebuildOptions code.

### CODE REVIEW

**Comment by ngokevin** [comment]
Thanks! I'll try to get around to looking at this. Very useful.

**Comment by ngokevin** [comment]
Thanks!

**Comment by ngokevin** [comment]
This might've affected search, I don't think it's working for me.

**Comment by ngokevin** [comment]
Does search work for you? Doesn't work well for me, not sure if it was broken before already.

**Comment by Adam4lexander** [comment]
It's not working for me either. There's a good chance I broke it since I was touching that code. Sorry about that I'll take a look and make a fix.

**Pull request merged**
