### PR TITLE
Update all dependencies and fix react code warnings

### LINKED ISSUE #641: Update all the dependencies, mainly webpack and react
I have a version of the inspector working with react 18.2.0, mainly changes about string refs that needs to be replaced by `React.createRef`, and `componentWillReceiveProps` by `componentDidUpdate` or `getDerivedStateFromProps`.
I'm waiting for #638 and #639 to be merged first, then I can proceed updating webpack to version 5, babel, react and other dependencies.

This will fix #606

### PR DESCRIPTION
**Pull request by vincentfretin**
Update all dependencies and fix react code warnings

This closes #641 and #601

Remaining todos:
- [ ] copy html to clipboard broken after the upgrade
- [ ] opening the textures modal doesn't work after the upgrade

### CODE REVIEW

**Comment by vincentfretin** [comment]
[gm](https://www.npmjs.com/package/gm), invariant, object-assign, [react-file-reader-input](https://www.npmjs.com/package/react-file-reader-input), eslint-plugin-promise, postcss-import were unused dependencies
[eslint-plugin-standard](https://www.npmjs.com/package/eslint-plugin-standard) is not needed anymore with latest eslint-config-standard
babel-core is replaced by @babel/core
babel-eslint is replaced by @babel/eslint-parser
babel-preset-env is replaced by @babel/preset-env
babel-preset-react is replaced by @babel/preset-react
babel-plugin-transform-class-properties is included as part of @babel/preset-env
terser-webpack-plugin-legacy removed, terser-webpack-plugin is a dependency of webpack 5, and enabled automatically when using mode: production.

**Comment by vincentfretin** [comment]
I rebased and push forced to add the fixes from #648
If you want to test, I pushed the build in my `code-cleanup-plus-react-update-with-dist` branch, it's the same commits as `code-cleanup-plus-react-update` but with an additional commit to push the build
```
<a-scene inspector="url:https://cdn.jsdelivr.net/gh/vincentfretin/aframe-inspector@f89a0b44190b1591d2d82f6f47ed7eecf4ef9b38/dist/aframe-inspector.min.js"
```

**Comment by vincentfretin** [comment]
Copy html to clipboard and opening the textures modal doesn't work. I'll look into it later.

**Comment by vincentfretin** [comment]
```
<a-scene inspector="url:https://cdn.jsdelivr.net/gh/vincentfretin/aframe-inspector@96b9ec69b4f1b5579cfd8d06d4b7971df64ace3a/dist/aframe-inspector.min.js"
```
includes the fix for https://github.com/aframevr/aframe-inspector/pull/638#issuecomment-1274323399

**Comment by vincentfretin** [comment]
Now using GLTFExporter directly from three package instead of the old one in vendor folder.

**Comment by dmarcos** [comment]
This needs rebase

**Comment by dmarcos** [comment]
Is it possible to break this down in smaller PRs?

**Comment by vincentfretin** [comment]
Now that all the other PRs are merged, this one contains only the big update of react and all dependencies. I could split the last commit in its own PR where I add husky but currently it depends on another commit that changes package-lock.json, that would be a headache to merge this commit first then rebase this PR. I can separate it when I'm done fixing the regression with the clipboard.

**Comment by dmarcos** [comment]
38k lines the package-lock.json file? Is not that a bit crazy 😄? Can it be purged / simplified? Adds tons of noise

**Comment by vincentfretin** [comment]
Ah ah no it can't be simplified, we need to commit the file as is.
It's just all the dependencies that are installed in a typical react app. The file is needed to install exactly those versions when you run `npm install`.
The package-lock.json in aframe repo is 25k lines. :)

**Comment by vincentfretin** [comment]
Thanks for merging, I'll fix the two remaining todos #662 asap.

**Pull request merged**
