### PR TITLE
Fixes #217 reposition and rename edit button

### LINKED ISSUE #217: Reposition and rename "edit/exit" button
From the discussion in https://github.com/aframevr/aframe-editor/issues/214 we're removing the menubar so we need to move the `edit/exit` button too.
I was thinking about changing the name to `Edit scene/Play scene` and to put the button at the botton centered horizontally.

Something like this:
screenshot 2016-07-19 19 58 05
screenshot 2016-07-19 19 57 59

### PR DESCRIPTION
**Pull request by fernandojsg**
screenshot 2016-07-19 20 39 23

### CODE REVIEW

**Comment by dmarcos** [comment]
Is the `edit button` also going to be at the center?

**Comment by dmarcos** [comment]
It doesn't seem to get a bit in the way? I understand you want to be consistent with the button position in edit/play mode. On the other hand we should keep the viewport as unobstructed as possible.

**Comment by fernandojsg** [comment]
If we can't use the top (left or right) corners we should probably use the bottom left corner? we could add some bar with the same width of the scenegraph, but I'm not sure, what do you think?

**Comment by fernandojsg** [comment]
Or what about adding a little bar on the top of the scenegraph, maybe with the `AFRAME` as we have before (if you click it will go to aframe.io or whatever) and in the right the `EDIT` button

**Comment by dmarcos** [comment]
We can add a toolbar at the top of the scenegraph. We could add the `export` ,`play`, `+` (to add an entity) buttons there.

**Comment by dmarcos** [comment]
I see a toolbar on top of the scenegraph to contain the actions that globally affect the scene.

**Comment by fernandojsg** [comment]
I'll close this PR to have just one removing the menu and moving the button.

**Pull request closed without merging**
