### PR TITLE
display tag name brackets in scenegraph

### PR DESCRIPTION
**Pull request by ngokevin**
screen shot 2016-07-13 at 12 22 33 pm

### CODE REVIEW

**Comment by fernandojsg** [comment]
cool change!

**Comment by dmarcos** [comment]
Should we do this for all of them?

**Comment by fernandojsg** [comment]
@dmarcos we're displaying `ID || tagName` so this is just for the ones with just `tagName`

**Comment by dmarcos** [comment]
I think it's more consistent and useful if you can see both all the time `<a-entity id="redBox">`. It reinforces the idea that the scene graph is actually the DOM

**Comment by fernandojsg** [comment]
but maybe that will make the scenegraph too wide, just thinking that we need to add icons there for actions for the entities, the visibility toggle icons (eyes),... it could take half of the screen

**Comment by dmarcos** [comment]
I know that adding `<a-scene>` makes the problem a bit worse but the scenegraph being too wide is already a problem with deep hierarchies. How are we going to deal with it?

**Comment by dmarcos** [comment]
Can we find a way to display the html tags without taking too much space? I think it's a good idea.

**Comment by fernandojsg** [comment]
What about something like this? (coder-colors). Adding the `< >` will helps also to differentiate the components' icons (if at the end we'll leave them there) from the entity actions icons, and it will give a better vision of the DOM.
screenshot 2016-07-14 00 28 16

**Comment by dmarcos** [comment]
I really like it. It conveys that those icons are part of the DOM too :). 
If you think about it there won't probably be many elements with IDs in the average experience so the wide scenegraph is less of a problem in practice. People use IDs to mark key elements in the page. I expect to see most of the entities with no ID.

**Comment by dmarcos** [comment]
How do we deal anyways with scengraphs with 3 or more depth levels? Is the scene graph panel adapting already the width?

**Comment by fernandojsg** [comment]
> I expect to see most of the entities with no ID.

Yep you're right

> How do we deal anyways with scenegraphs with 3 or more depth levels? Is the scene graph panel adapting already the width?

Right now is not adapting, but we could make it adapt. I also don't expect to have so many depth levels and even if you have them. 
Another option is to make it fixed size and add scroll when needed (maybe after 3 levels) and the user could horizontal scroll (I know that sucks) or change the size of the sidebar. But probably this one is harder to implement too.

**Comment by fernandojsg** [comment]
Unity even doesn't support horizontal scrolling, you need to resize the scenegraph.
screenshot 2016-07-14 01 18 43

**Pull request merged**
