### PR TITLE
added styling for scroll-bar

### PR DESCRIPTION
**Pull request by odGit**
This it an initial changes for issue #297
I would like to hear you feedback and maybe some sketch of how you would like it.

### CODE REVIEW

**Comment by fernandojsg** [comment]
Hi @odGit ! thanks for helping with that.
I don't have much experience with styling scrollbars, but is not possible to style it also on firefox? I've see it working just on chrome.
About the style, I believe @feiss could help here giving some tips as he's taking care of the overall inspector aesthetics.

**Comment by feiss** [comment]
afaik, the only way of styling scrollbars in firefox is not using native scrollbars, but a js library like https://www.npmjs.com/package/react-scrollbar

**Comment by odGit** [comment]
Thanks @feiss, I will have a look at this one.

**Comment by fernandojsg** [comment]
It looks like they didn't update it for a while and it has many bugs, some of them related to dynamically modify the height of the container. So I don't feel quite confident about using it.
Maybe we could just define an style for chrome and leave firefox for another PR if we find a more stable scrollbar solution.

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe-inspector/commit/c49af2ed2adcc674d1e2e4354c149ea462d9102f

**Pull request closed without merging**
