### PR TITLE
Export to .glb with embedded images.

### LINKED ISSUE #547: glTF export uses absolute URLs to images
I think it would be preferable to always embed images, or at least give the option. When absolute image URLs are used, I can't import the resulting `.gltf` into Blender and validation gives errors.

### LINKED ISSUE #551: Aframe inspector: glTF export button broken/ not working as expected
Trying to export my aframe scene using this button was not initiating a download at all,

Instead I selected the entity and exporting that as a glTF using the button on the right and it would download

attempting to re-display the model in aframe was causing issue and I was advised to try viewing it on

https://gltf-viewer.donmccurdy.com/
to which the response was missing texture:

    A-Frame Version: 0.8.2
    Platform / Device: OSX chrome

### PR DESCRIPTION
**Pull request by donmccurdy**
@fernandojsg  I believe this PR fixes #547 and fixes #551, but due to #552 I am not sure how to test this locally.

### CODE REVIEW

**Comment by fernandojsg** [comment]
@donmccurdy after a quick pass I've just tried it and it "works" but the .glb file contains just `[object Object]`. I'll check the code to see what is going wrong.

But I don't get any error because of https://github.com/aframevr/aframe-inspector/issues/552 I can't reproduce it /cc @dmarcos @ngokevin any idea what could be causing it?

**Comment by fernandojsg** [comment]
@donmccurdy I believe one of the needed steps is to update `GLTFExporter.js` with an updated version from three.js that supports `binary: true` :D

**Comment by donmccurdy** [comment]
Ok, I think this is working now — updated GLTFExporter, marked inspector helpers (see https://github.com/aframevr/aframe-inspector/issues/523#issuecomment-384522834), and filtered them out while exporting.

**Comment by arpu** [comment]
i had some time to test this! and it works fine

**Comment by fernandojsg** [comment]
Yeah, thanks for remind me I forgot about this one! Thanks @donmccurdy and @arpu

**Comment by arpu** [comment]
@donmccurdy  if i use 
    map.wrapS = THREE.RepeatWrapping;
     map.wrapT = THREE.RepeatWrapping;
    map.repeat.x = 20;
     map.repeat.y = 20;
and export the generated gltf model this is not applied to the exported model 
is this a known problem ?

**Comment by donmccurdy** [comment]
Texture repeat, rotation, and offset are not part of the core glTF spec, but require a very recent extension. The THREE.GLTFLoader implementation has not been merged yet (https://github.com/mrdoob/three.js/pull/13831), and no PR for THREE.GLTFExporter exists yet.

EDIT: The wrapS / wrapT part should already be supported, though: https://github.com/mrdoob/three.js/blob/dev/examples/js/exporters/GLTFExporter.js#L740-L741

**Pull request merged**
