### PR TITLE
add visible borders to number/string inputs (related to issue #29)

### PR DESCRIPTION
**Pull request by cvan**
## before

before
## after

after

### CODE REVIEW

**Comment by cvan** [comment]
this is just a tweak. to completely close #29, all numeric fields should be properly changed from `input.number` to `<input type="number">`/`<input type="range">`

**Comment by fernandojsg** [comment]
Do you think we should center or align right the numbers with the new style?

**Comment by caseyyee** [comment]
I think having a box around the numbers helps make it easy to see that it's a editable field.  Also helps with the readability of the numbers as well.   In this case, it's aligned-left:

image

(Sketch)

We can use underlines in place of boxes.  As long as we are consistent.

Also like that they have X, Y clearly labeled for the fields.

**Comment by cvan** [comment]
👍 to Sketch's treatment

**Comment by ngokevin** [comment]
https://github.com/aframevr/aframe-inspector/commit/ecb20458259544ac08925109d2ed557fb72581eb

**Pull request closed without merging**
