### PR TITLE
added new icons for copy html and delete component

### PR DESCRIPTION
**Pull request by feiss**

### CODE REVIEW

**Comment by fernandojsg** [comment]
What about converting the svg to a font instead? With an app like https://icomoon.io/app I could give it a try. As we're going to have many icons it could be more useful

**Comment by dmarcos** [comment]
I've used icomoon in the past. It's good.

**Comment by fernandojsg** [comment]
@feiss what about adding the icons using `iconomoon` and add the font to the source to the repo so we could keep adding the images there incrementally so we could remove fontawesome icons in the future

**Comment by feiss** [comment]
yup, I'd switch to iconmoon

**Comment by ngokevin** [comment]
outdated, feiss will probably do in a bit in a new pr

**Pull request closed without merging**
