### PR TITLE
Added this.emit = Events.emit to add possibility to emit custom events from outside the Inspector class.

### PR DESCRIPTION
**Pull request by gregogalante**
Added this.emit = Events.emit to add possibility to emit custom events from outside the Inspector class.

### CODE REVIEW

**Comment by vincentfretin** [comment]
It would make sense to also expose `this.off = Events.off;` so you can remove a listener you added previously with AFRAME.INSPECTOR.on. (Ok just saw you added it)

**Comment by vincentfretin** [comment]
I would be interested of knowing your use case with this, creating entity with the entitycreate event maybe? You can DM me on discord (handle vincentfretin) for a quick chat.
I myself have the whole aframe-inspector code in my own repo under src/editor. This is also what 3dstreet is doing now, so we're just importing Events. We're also working on a new json import/export of the scene, see https://github.com/3DStreet/3dstreet/pull/537

**Comment by dmarcos** [comment]
Thanks so much. Congrats on your first contribution @gregogalante

**Comment by vincentfretin** [comment]
Did you forgot to push the Merge button @dmarcos?

**Comment by dmarcos** [comment]
thanks

**Comment by vincentfretin** [comment]
This was not working. It will be reverted in #755

**Pull request merged**
