### PR TITLE
Fix TextureWidget componentDidUpdate to not crash React UI on aframe 1.6.0

### LINKED ISSUE #722: React UI disappear when selecting a entity with texture on aframe 1.6.0 (works ok on aframe 1.5.0)
Tested on the index.html from this repo, on aframe 1.5.0 no issue, on aframe 1.6.0, when selecting an entity with a texture, the cube or the floor, we get the stacktrace
```
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27287:11)
    at scheduleUpdateOnFiber (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:25470:3)
    at Object.enqueueSetState (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14067:7)
    at Component.setState (webpack-internal:///./node_modules/react/cjs/react.development.js:355:16)
    at TextureWidget.setValue (webpack-internal:///./src/components/widgets/TextureWidget.js:206:12)
    at TextureWidget.componentDidUpdate (webpack-internal:///./src/components/widgets/TextureWidget.js:145:14)
    at commitLayoutEffectOnFiber (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23333:28)
    at commitLayoutMountEffects_complete (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:24683:9)
    at commitLayoutEffects_begin (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:24669:7)
    at commitLayoutEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:24607:3)
```
and the React UI disappear. 

in TextureWidget.js:206:12
```
    console.log(newValue, this.state.value);
    if (newValue && newValue !== this.state.value) {
      this.setValue(newValue);
    }
```
on aframe 1.6.0, it gives
`,  '#crateImg'`

on aframe 1.5.0, it gives
`#crateImg, #crateImg`

### PR DESCRIPTION
**Pull request by vincentfretin**
This closes #722

### CODE REVIEW

**Comment by vincentfretin** [comment]
Note this PR is okay to be merged, it doesn't crash anymore when you select an entity with a texture, but there is still an issue of changing the texture that's being discussed in #722

**Comment by vincentfretin** [comment]
Okay, I just verified with aframe master by copying a build manually, the issue of changing the texture on the cube is definitely fixed with both this change and the changes from https://github.com/aframevr/aframe/pull/5544
You can merge @dmarcos

**Comment by vincentfretin** [comment]
I'm confirming https://github.com/aframevr/aframe/pull/5549 fixes the issue of removing the texture on the cube.
@dmarcos can you please merge?

**Comment by dmarcos** [comment]
Thanks!

**Pull request merged**
