### PR TITLE
Fix panels disappearing when selecting a-videosphere entity

### PR DESCRIPTION
**Pull request by vincentfretin**
See details of the debugging issue in https://github.com/aframevr/aframe/issues/5257
This fixes panels disappearing when selecting a-videosphere entity
Capture d’écran du 2023-03-14 11-31-44

### CODE REVIEW

**Comment by dmarcos** [comment]
Thanks so much! Do we need to commit the dist?

**Comment by vincentfretin** [comment]
It's good to have an updated dist on master yes, this way we can use 
```<a-scene inspector="url: https://cdn.jsdelivr.net/gh/aframevr/aframe-inspector@master/dist/aframe-inspector.min.js">```
without waiting for a 1.4.2 release.

**Comment by vincentfretin** [comment]
But your call really. I can remove the commit if you want. And you do the dist and commit it yourself, right after the merge or wait for a new release. Let met know.

**Comment by dmarcos** [comment]
Problem is that it makes the PRs noisy. Maybe remove for now and can think of setting a build bot like in A-Frame

**Comment by vincentfretin** [comment]
I removed the dist.

**Comment by dmarcos** [comment]
Thanks so much!

**Pull request merged**
