### PR TITLE
Add link to components' docs. Fixes #31

### LINKED ISSUE #31: Consider adding links to the docs for each component + property
image

Definitely could come later, but it'd be nice if there was some (?) help icon or something that could link me to the docs to learn about it.

### PR DESCRIPTION
**Pull request by fernandojsg**
Added `help` link button for each core component.
screenshot 2016-07-15 19 59 34

### CODE REVIEW

**Comment by dmarcos** [comment]
Should we alphabetize the labels?

**Comment by ngokevin** [comment]
How about the question mark bubble:

`MATERIAL (?)`

Which would help separate it from the actual actions.

**Comment by fernandojsg** [comment]
yep, I like @ngokevin proposal, it help separate and it's also smaller.

**Comment by dmarcos** [comment]
We could just make the whole component title clickable. The `?` symbol would just reinforce that there's help available.

**Comment by fernandojsg** [comment]
I would expect to click the title and to toggle visibility of the panel, if it will launch the help, I will need to be very careful to click on the empty space outside the actions and title

**Comment by ngokevin** [comment]
I could see collapse attempts unintentionally opening links.

**Comment by fernandojsg** [comment]
Yep, same here. So maybe just use some clickable icon like http://fontawesome.io/icon/info-circle/ or http://fontawesome.io/icon/question-circle/ next to the title?

**Comment by fernandojsg** [comment]
I've added the icon button next to the title:
screenshot 2016-07-19 13 01 22

**Pull request merged**
