### PR TITLE
Delete aframe.js (ancient & unused copy of code from 0.4.0)

### PR DESCRIPTION
**Pull request by diarmidmackenzie**
Following on from https://github.com/aframevr/aframe/pull/5333 and based on comments from @vincentfretin, I checked aframe-inspector for any usage of 'https://cdn.aframe.io'.

The only instances I found were in the module examples\js\aframe.js.

This appears to be a copy of the 0.4.0 distribution of A-Frame, and not used by any of the examples.  I believe it can be deleted, and it would be good housekeeping to do so.

Hence this PR.

### CODE REVIEW

**Review by vincentfretin — APPROVED** [review]
Yes indeed.

**Comment by vincentfretin** [comment]
The list of textures images I talked about in comment https://github.com/aframevr/aframe/issues/5119#issuecomment-1382752776 is retrieved via https://aframe.io/sample-assets/dist/images.json when you open the texture modal.
The url is defined here https://github.com/aframevr/aframe-inspector/blob/72fd46159801ad37a14e87448611607b5d09a36e/src/lib/assetsLoader.js#L3 but that's different from https://cdn.aframe.io/ so you can't use AFRAME_ROOT_CDN here. If we introduce another configurable constant, that can be done in another PR. But also this feature should maybe be dropped completely, see #676

**Comment by vincentfretin** [comment]
For my comment above, I created #702 

@dmarcos this PR just remove an unused file, you can merge.

**Comment by dmarcos** [comment]
Thanks!

**Pull request merged**
