### PR TITLE
fix: #674 cannot use 'in' operator to search

### PR DESCRIPTION
**Pull request by niksonleonard**

### CODE REVIEW

**Comment by vincentfretin** [comment]
Those changes aren't needed, the code is working as expected. See my comment
https://github.com/aframevr/aframe-inspector/issues/674#issuecomment-1429449038

**Comment by niksonleonard** [comment]
ok, if you say so 🤗

**Comment by vincentfretin** [comment]
Do you confirm my assumption you're using react? and replacing `wasd-controls` by `wasd-controls=""` fixes the issue? If not please provide a reproduction example.

**Comment by dmarcos** [comment]
Can we close this?

**Comment by dmarcos** [comment]
I think it's no longer needed but can reopen if necessary. Thanks so much

**Comment by uurcank** [comment]
@dmarcos  this is still an issue for me. is there any fix merged to the repo?

**Comment by vincentfretin** [comment]
@uurcank If you're using react, please be sure you use `=""`.
If you have an issue, please create another issue with an example on glitch.

**Pull request closed without merging**
