### PR TITLE
Adjustments for THREE r144

### PR DESCRIPTION
**Pull request by vincentfretin**
Some fixes to work with aframe master (tested against three r141 and not r144 because there is no updated build currently on aframe repo) and fixing some issues I found while testing, see each commit for details.

### CODE REVIEW

**Comment by kylebakerio** [comment]
I tested the provided demo scene pretty thoroughly, was not able to get any inspector-specific issues to occur. This is great work that really fixes a lot of nagging minor issues that have plagued the inspector for some time and bring it up to date, great stuff.

**Comment by kylebakerio** [comment]
I made a pull request against aframe-environment-component accordingly, [here](https://github.com/supermedium/aframe-environment-component/pull/78).

**Comment by dmarcos** [comment]
Can we separate in different PRs the adjustments for THREE r144 and the rest?

**Comment by vincentfretin** [comment]
Sure, I rebased and kept only relevant commits to the threejs upgrade. The other commits are in #638

**Comment by dmarcos** [comment]
Thank you! 👏

**Pull request merged**
