### PR TITLE
Attaches editor to the AFRAME global variable

### PR DESCRIPTION
**Pull request by dmarcos**

### CODE REVIEW

**Comment by fernandojsg** [comment]
It will break all the references to `editor` in the rest of the code.

**Comment by dmarcos** [comment]
I think your code should not use the externally exposed API

**Comment by dmarcos** [comment]
changing the public facing API should not affect the code internally

**Comment by dmarcos** [comment]
I made the editor expose a singleton instead of the constructor. The other modules import it instead of relying in the editor variable of the window object. This way we decouple the internal from the publicly exposed API.

**Comment by fernandojsg** [comment]
superb! thank you :)

**Pull request merged**
