### PR TITLE
remove sidebar width

### PR DESCRIPTION
**Pull request by arpu**
with this i can see all entity
bildschirmfoto von 2018-03-11 02-10-00

### CODE REVIEW

**Comment by ngokevin** [comment]
Hmm on lower res screens, this would make the entity panel cover the scene. Sure there's a way to compromise

**Comment by arpu** [comment]
this is how its looks now on ipad 
so adding x scrolling on the sidebar ? 

bildschirmfoto von 2018-04-09 21-04-10

**Comment by ngokevin** [comment]
Does the sidebar not scroll already? If it doesn't, yeah, let's add x scrolling.

**Comment by arpu** [comment]
no it does not scroll :/ i have no idea how i can add the scrolling :/

**Comment by arpu** [comment]
will open a new pull request with x scrolling

**Pull request closed without merging**
